// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: image.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImageServiceClient is the client API for ImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageServiceClient interface {
	// Method to send an image byte stream.
	SendImage(ctx context.Context, opts ...grpc.CallOption) (ImageService_SendImageClient, error)
}

type imageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageServiceClient(cc grpc.ClientConnInterface) ImageServiceClient {
	return &imageServiceClient{cc}
}

func (c *imageServiceClient) SendImage(ctx context.Context, opts ...grpc.CallOption) (ImageService_SendImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &ImageService_ServiceDesc.Streams[0], "/ImageService/SendImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageServiceSendImageClient{stream}
	return x, nil
}

type ImageService_SendImageClient interface {
	Send(*ImageData) error
	Recv() (*ImageData, error)
	grpc.ClientStream
}

type imageServiceSendImageClient struct {
	grpc.ClientStream
}

func (x *imageServiceSendImageClient) Send(m *ImageData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *imageServiceSendImageClient) Recv() (*ImageData, error) {
	m := new(ImageData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImageServiceServer is the server API for ImageService service.
// All implementations must embed UnimplementedImageServiceServer
// for forward compatibility
type ImageServiceServer interface {
	// Method to send an image byte stream.
	SendImage(ImageService_SendImageServer) error
	mustEmbedUnimplementedImageServiceServer()
}

// UnimplementedImageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedImageServiceServer struct {
}

func (UnimplementedImageServiceServer) SendImage(ImageService_SendImageServer) error {
	return status.Errorf(codes.Unimplemented, "method SendImage not implemented")
}
func (UnimplementedImageServiceServer) mustEmbedUnimplementedImageServiceServer() {}

// UnsafeImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageServiceServer will
// result in compilation errors.
type UnsafeImageServiceServer interface {
	mustEmbedUnimplementedImageServiceServer()
}

func RegisterImageServiceServer(s grpc.ServiceRegistrar, srv ImageServiceServer) {
	s.RegisterService(&ImageService_ServiceDesc, srv)
}

func _ImageService_SendImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImageServiceServer).SendImage(&imageServiceSendImageServer{stream})
}

type ImageService_SendImageServer interface {
	Send(*ImageData) error
	Recv() (*ImageData, error)
	grpc.ServerStream
}

type imageServiceSendImageServer struct {
	grpc.ServerStream
}

func (x *imageServiceSendImageServer) Send(m *ImageData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *imageServiceSendImageServer) Recv() (*ImageData, error) {
	m := new(ImageData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImageService_ServiceDesc is the grpc.ServiceDesc for ImageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ImageService",
	HandlerType: (*ImageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendImage",
			Handler:       _ImageService_SendImage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "image.proto",
}
